### ISSUE TITLE
How do I use the QtQuick.Controls style without qmake?

### ISSUE THREAD

**Issue by mottosso** [papyros/qml-material#162]
After updating the repo, I started getting this error.

```
QtQuick.Controls.Styles.Material is not installed
```

Coming in from `Button.qml`.

```qml
import QtQuick.Controls.Styles.Material 0.1 as MaterialStyle
```

**To reproduce**

The way I've installed it previously was to append `qml-material/modules` and `qml-extras/modules` to the `QML2_IMPORT_PATH` which worked well.

I understand that there is an official way involving `make`, but since I'm using a pre-compiled version of PyQt5 with no access to `make`, I had to resort to manually appending to the import path instead.

I noticed that the breaking change came from here: https://github.com/papyros/qml-material/commit/c79c7b5cea72600173a2c01e220960b7ec6e5800

Where a folder is being added to the internal libraries of Qt, here

```
$$[QT_INSTALL_QML]/QtQuick/Controls/Styles/Material
```

**Solution**

The solution I came up with was to manually copy over the `/styles/material` directory into my PyQt5 installation.

**Question**

Why break encapsulation of your QML module and resort to injecting modules into the internal Qt QML libraries? Do you have any recommendations on how to more easily install qml-material for PyQt users?

Thanks

**Comment by iBeliever** [comment]
First of all, this is not "breaking encapsulation of our QML module and resorting to injecting modules into the internal Qt QML libraries." This is the standard way to create a theme for QtQuick.Controls that, when set as the system theme, will be used by all QtQuick.Controls apps. What we're doing inside the Material components which extend QtQuick.Controls components is directly specifying the theme so that apps built without our framework use the Material Design style, regardless of the system style.

With the style installed properly, it can be set as the global QtQuick.Controls theme using:

    export QT_QUICK_CONTROLS_STYLE=Material

(But again, this isn't necessary for apps built using our framework, as it will force the use of the Material style.)

Now that that is clear, on to how to solve your requirements. You can easily fix this by doing:

    mkdir -p modules/QtQuick/Controls/Styles
    ln -s ../../../../styles/material modules/QtQuick/Controls/Styles/Material

That will allow you to just add `qml-material/modules` to your import path, and the style should work just fine.

Hope this helps!

**Comment by mottosso** [comment]
> This is the standard way to create a theme for QtQuick.Controls that, when set as the system theme, will be used by all QtQuick.Controls apps.

Ah, I did not know that, thanks for letting me know and sorry for the confusion. Is there anywhere I can read up on this standard?

> export QT_QUICK_CONTROLS_STYLE=Material

That is really cool, thanks for letting me know.

> Now that that is clear, on to how to solve your requirements. You can easily fix this by doing:

Yes, as mentioned, I did copy the directory into the `/Controls` directory and it did work. I didn't understand that this was standard and assumed I was hacking, but seeing as it is this is not a problem.

Thanks for a swift reply!

**Comment by iBeliever** [comment]
@mottosso I can't find any official documentation on this. However, custom QtQuick.Controls styles are used by KDE/Plasma (Breeze), Maui's Hawaii desktop (Wind), plus others that I'm not familiar with.

Back to your original issue, what I've done is moved the style under the `modules` directory. This means all you have to do is add the `modules` directory to your import path as you were doing before we split out this style. This will make it very easy for developers to use the framework standalone, without installing it globally or using symlinks.

**Comment by mottosso** [comment]
> what I've done is moved the style under the modules directory.

Ah! That worked well for me. Thanks a lot!
