### ISSUE TITLE
In the test.pro file Sixth 'IMPORTPATH += $$PWD/../modules'

### ISSUE THREAD

**Issue by xchz** [papyros/qml-material#176]
i can not find qmake variable 'IMPORTPATH' in qt website http://doc.qt.io/qt-5/qmake-variable-reference.html.Compile error.

**Comment by iBeliever** [comment]
Hi there. Can you share what version of Qt 5 you have and include the error you're getting? Thanks!

**Comment by xchz** [comment]
Compiled with Qt version 5.4.0
Running with Qt library version 5.4.0

make: Interrupt/Exception caught (code = 0xc00000fd, addr = 0x420942)

i has read qml-material.pro and test.pro,first will run test project,right?But the test project depend on ”modules “ directory ,so i find this line " IMPORTPATH += $$PWD/../modules " in test.pro . 
Here is all qmake variable http://doc.qt.io/qt-5/qmake-variable-reference.html
Why i can not find IMPORTPATH? So test project can not compile.

The result is copy directory "modules\Material " to $$[QT_INSTALL_QML]/Material and copy directory "modules\QtQuick\Controls\Styles\Material" to "$$[QT_INSTALL_QML]/QtQuick/Controls/Styles/Material".

But i find that the directory "modules\Material " and "modules\QtQuick\Controls\Styles\Material" did not copy to the corresponding directory. So i copy the diectory to the corresponding directory by myself and test project can compile.

**Comment by iBeliever** [comment]
The `IMPORTPATH` option is a valid option, and comes from the [QtQuick test framework](http://doc.qt.io/qt-5/qtquick-qtquicktest.html).

I'm not sure why you're having issues. I'm on OS X and Arch Linux with Qt 5.4 and the alpha of Qt 5.5, and don't have any problems. Since this isn't a problem specific to our library, you'll get more help if you take this to a general Qt support site, such as the Qt forums or Stack Overflow.

**Comment by xchz** [comment]
thank you
