### ISSUE TITLE
Why not adopt MIT license /Apache License ?

### ISSUE THREAD

**Issue by sheafferusa** [papyros/qml-material#253]
Hi, 
They are also officially supported by google and gives a much better chance for the software involved to reach many more  people/users than if the project goes for GPL(LGPL) kinds of stuffs.

**Comment by VirusKA** [comment]
is this really an issue?

**Comment by proninyaroslav** [comment]
You important endorsement "good corporations"? I feel sorry for you. Using other licenses gives no advantages.

**Comment by koloboid** [comment]
MIT/Apache is not an option, as for me. But commercial licence must be.

**Comment by proninyaroslav** [comment]
@koloboid,
LGPL intended for this purpose.

**Comment by sheafferusa** [comment]
WoW! I expected sensible arguments instead of blatant trash talks. I really feel discouraged at the lack of professionalism out here. I just hope, there's someone here, (who is serious about the project and is directly involved in its development) who might be interested to discuss the issues opened here. If not, then, it would probably be better to just close the issue rather than wasting time over it.

Regards,
Anime.sh

**Comment by proninyaroslav** [comment]
@sheafferusa ,
I think this is an ordinary trolling and provocation on your part.

**Comment by koloboid** [comment]
@proninyaroslav,
LGPL is not acceptable by some mobile markets (AppStore?). What for google material on iOS - is another question :)
Also, commercial licence would allow to support papyros project financially.

**Comment by iBeliever** [comment]
Come on everyone, let's keep the conversation pleasant please :)

As @koloboid LGPL does not seem to be accepted into the iOS App Store. No of course, Material Design on mobile is for Android, and iOS has their own guidelines, but I can see developers wanting to use it on iOS as well, just as Google is doing.

So, we have two options: (1) dual-license, with the current LGPL and a new commercial license, with licensing costs going to bug bounties, or (2) switch to a more permissive license that is allowed on iOS.

I'm worried about going with (2) because that would allow people to make changes and not contribute them back upstream. (1) would be nice, but would require us to set uo some sort of licensing/payment infrastructure.

Regardless, we'd need to contact all of the 29 contributors and ask their permission for us to change the license. We might also need a contributor license agreement (CLA), not sure on that one.

**Comment by marco-piccolino** [comment]
@iBeliever instead of setting up a payment infrastructure, wouldn't a required Bountysource (in case of one-off payments) or Bountysource Salt (in case of recurring payments, and provided you're still up for it) donation be an option? Also, do you have in mind a likely amount for the commercial license?

**Comment by marco-piccolino** [comment]
@koloboid why is MIT/Apache not an option for you?

**Comment by SShrike** [comment]
What about the Mozilla Public License?

**Comment by koloboid** [comment]
@marco-piccolino personally, I'm fully accepts MIT, but as @iBeliever said - this allows people to not to contribute any improvements back. Don't forget, that qml-material is only a part of something bigger (PapyrOS). Also, GPL guarantees the freedom of the project future. The only thing - many people just afraid GPL (but still uses Qt under the same LGPL terms)

**Comment by cicku** [comment]
Why do some blind people still hold opinion like Google is not an evil company, as a result something they use is always the best choice?

**Comment by marco-piccolino** [comment]
Chris, this is definitely off topic. Please let us be respectful to other
people's opinions as different as they might be from our own, and let's
keep the focus on the topic. Thanks!
Il 13/set/2015 09:52 AM, "Christopher Meng" <notifications@github.com> ha
scritto:

**Comment by cicku** [comment]
No, I'm not off topic. If someone started a debate with such argument, then I must say it doesn't make sense.

Apple is enjoying the freedom yet it is denying its users enjoying the same, ridiculous but seems understandable.

You all have and only have 1 solution, dual licence. Dual licence to BSD/MIT/Public Domain. And people who use this project and release app in AppStore or whatever else must use commercial licence. 

Will they ever use this? We don't know.

**Comment by marco-piccolino** [comment]
@cicku thanks, now I get your point of view

**Comment by marco-piccolino** [comment]
there is an opinion post here that talks about the various licensing options that were mentioned. You might not agree, but I guess it's worth a read: https://forum.syncthing.net/t/discussion-of-license-implications-gpl-lgpl-mpl2-mit-ios-app-stores/2002

**Comment by aleixpol** [comment]
@iBeliever Using LGPL doesn't force contributions to go back to upstream. Otherwise all linux distros would be illegal. It only ensures that they will remain free software (or it will be an illegal fork).

To solve the iOS issue, VLC dual-licensed to MPL (additionally to GPL):
```VLC for iOS is bi-licensed under the Mozilla Public License Version 2 as well as the GNU General Public License Version 2 or later. You can modify or redistribute its sources under the conditions of these licenses. Note that additional terms apply for trademarks owned by the VideoLAN association.```

HTH, hoping I didn't feed any trolls. ^^

**Comment by iBeliever** [comment]
@aleixpol Sorry if I was unclear. What I meant was that the LGPL prevents someone from taking our work, making a proprietary fork, and then either profiting from it or making significant improvements that we wouldn't have access to.

Thanks for your feedback on the licensing issue. I'll look into the MPL license.

**Comment by iBeliever** [comment]
We'll be using the MPL, see #361.
