### ISSUE TITLE
Loader loads the same qml document twice? A Bug?

### ISSUE THREAD

**Issue by nasibai228** [papyros/qml-material#295]
I was playing with the `demo` project when noticed that `Loader` type loads QML-document twice. I changed the name of a document to call for causing an error to capture it:
![A Bug](http://i.imgur.com/klX9Lse.jpg)
The calling is described here AFAIK:
```qml
source: {
    if (navDrawer.enabled) {
        return Qt.resolvedUrl("%1Demo.qml").arg(demo.selectedComponent.replace(" ", ""))
    } else {
        return Qt.resolvedUrl("%1Demo.qml").arg(selectedComponent.replace(" ", ""))
    }
}
```
**And I have 2 questions about it:**
0. Is this a bug?
1. Why do we have 2 different implementation for 2 state of `navDrawer`. In the 1st one we choose `selectedComponent` through the `id` of the application and in the 2nd one we use directly. Why?

**Comment by iBeliever** [comment]
Yes, this is probably a bug. I'll look into it. As for the reason why we have two different implementations, the reason is that one gets the selected component shared across all tabs when the tabs are hidden and a component is selected via the nav drawer. The second gets a per-tab selected component, so we can save the selected component when switching between tabs.

**Comment by iBeliever** [comment]
@nasibai228 Why'd you close this? I haven't had a chance to look into why the error was occuring twice.

**Comment by nasibai228** [comment]
@iBeliever oh, I'm sorry. I was thinking if have figured out the problem the issue should be closed by myself. My bad. Again, I'm sorry.
