### ISSUE TITLE
Remove hard dependency on ECM (KDE Frameworks)

### ISSUE THREAD

**Issue by geiseri** [papyros/qml-material#384]
Right now it is not clear why ECM is needed for cmake.  This causes issues for embedded installations that do not require KDE to run Qt only applications.  Is KDE frameworks going to become a hard dependency in the future?
##

**Comment by kingwill101** [comment]
it would be best to maintain both a qmake  and a cmake file

**Comment by habemus-papadum** [comment]
I also find the ECM dependency inconvenient   The best thing about providing a cmake or autoconf  build is that one can usually install software simply in one or two steps, but ECM creates a hassle if you are not using KDE.  In general, since this project is pure qml, the build is doing almost nothing (e.g. one can simply git clone, and then qmlscene -I modules demo/main.qml, and be up and running (perhaps you should mention this on your readme...) furthermore you already have a standalone script that is not cmake based to create qrc files.   Perhaps having one .pro based project (which would require almost no maintenance) that includes both the main qmlproject and demo qmlproject so that users can  quickly load everything into qt creator, run the demo, debug, hack, etc and also a minimal cmake file that can be used to install the module content and qrc's to a user specified prefix?  The current setup is nearly 80% there, but in its current state is not newbie friendly.  thanks for the great work!

**Comment by iBelieve** [comment]
The point of the ECM dependency was to make it easier to install in the correct place. My assumption was that most app developers on platforms other than Linux would want to include QML Material locally instead of installing globally with CMake. Since it seems like the ECM dependency is causing more problems than good, I'll look into dropping it.

**Comment by habemus-papadum** [comment]
That's a reasonable motive -- If get a sec this week, I'll try sending you a PR that does something reasonable if ECM is not found, and maybe for a while you can try both options

**Comment by iBelieve** [comment]
We've switched back to QMake to make it easier for developers and to work better with QPM.
