### ISSUE TITLE
Missing material.extras httplib.js etc.

### ISSUE THREAD

**Issue by jorisvergeer** [papyros/qml-material#422]
Hi,

During the big refactoring last month some javascript files I used were removed. Your httplib and promise libs were quite nice. 

Are they available somewhere else and it would be nice if they also become licensed under MPL as well.

Joris

**Comment by iBelieve** [comment]
Those libraries were nice, but the problem was they were custom implementations and didn't follow any particular standardized spec (ES6 promises or Promises/A+, for example). Another project I'm working on lets you use ES6 promises and the new fetch API, which both are standardized (actually, taken straight from standard npm packages): https://github.com/quickly/quickly (while that project is geared towards a full ES6/Node.js emulation layer, it works perfectly fine for just including the Promise and fetch APIs).
